name = "HidApi"
uuid = "39e74766-396e-420b-955c-dcb1d9319e05"
authors = ["Gerhard Aigner <gerhard.aigner@gmail.com>"]
version = "1.1.0"

[deps]
hidapi_jll = "fc16ec7e-3cba-5ca4-a17a-1acd8165bbee"

[compat]
hidapi_jll = "0.11.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
